export const services = [
	{
		id: 1,
		name: "Screen Replacement",
		price: 100,
		type: "Hardware",
		description: "Cracks & touch issues",
		icon: "Smartphone",
	},
	{
		id: 2,
		name: "Battery Replacement",
		price: 70,
		type: "Hardware",
		description: "Fast power restore",
		icon: "BatteryCharging",
	},
	{
		id: 3,
		name: "Water Damage Repair",
		price: 120,
		type: "Diagnostics",
		description: "Liquid diagnostics",
		icon: "Droplet",
	},
	{
		id: 4,
		name: "Charging Port Repair",
		price: 60,
		type: "Hardware",
		description: "Loose / no charge",
		icon: "Usb",
	},
	{
		id: 5,
		name: "Camera Repair",
		price: 90,
		type: "Hardware",
		description: "Blurry or dead camera",
		icon: "Camera",
	},
	{
		id: 6,
		name: "Speaker Repair",
		price: 50,
		type: "Hardware",
		description: "Low or distorted sound",
		icon: "Volume2",
	},
	{
		id: 7,
		name: "Motherboard Repair",
		price: 200,
		type: "Diagnostics",
		description: "Advanced diagnostics",
		icon: "Cpu",
	},
	{
		id: 8,
		name: "Button & Sensor Repair",
		price: 45,
		type: "Hardware",
		description: "Power & fingerprint issues",
		icon: "Fingerprint",
	},
];

export const timeSlots = [
	"09:00 AM",
	"10:00 AM",
	"11:00 AM",
	"12:00 PM",
	"01:00 PM",
	"02:00 PM",
	"03:00 PM",
	"04:00 PM",
	"05:00 PM",
];
